import * as Types from '../../__generated__/gql-types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type cpMeQueryQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type cpMeQueryQuery = { __typename?: 'Query', cp_me: { __typename?: 'CP_MeOutput', id: number, mainId: string, name: string, number: number, position: Types.POSITION, money: number, joinclasspay: { __typename?: 'CP_PaysObj', id: number, user_id: number, className: string, schoolName: string, classTh: number, imgurl: string, moneyUnit: string, numberOfDigits: number, isTrade: boolean } } };


export const cpMeQueryDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"cpMeQuery"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"cp_me"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"mainId"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"number"}},{"kind":"Field","name":{"kind":"Name","value":"position"}},{"kind":"Field","name":{"kind":"Name","value":"money"}},{"kind":"Field","name":{"kind":"Name","value":"joinclasspay"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"user_id"}},{"kind":"Field","name":{"kind":"Name","value":"className"}},{"kind":"Field","name":{"kind":"Name","value":"schoolName"}},{"kind":"Field","name":{"kind":"Name","value":"classTh"}},{"kind":"Field","name":{"kind":"Name","value":"className"}},{"kind":"Field","name":{"kind":"Name","value":"imgurl"}},{"kind":"Field","name":{"kind":"Name","value":"moneyUnit"}},{"kind":"Field","name":{"kind":"Name","value":"numberOfDigits"}},{"kind":"Field","name":{"kind":"Name","value":"isTrade"}}]}}]}}]}}]} as unknown as DocumentNode<cpMeQueryQuery, cpMeQueryQueryVariables>;