import * as Types from './__generated__/gql-types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type CPUserBasicPartsFragment = { __typename?: 'CP_User', id: number, mainId: string, number: number, name: string, position: Types.POSITION, money: number };

export type CPPayPartsFragment = { __typename?: 'CP_Pay', id: number, user_id: number, className: string, schoolName: string, classTh: number, classNum: number, code: string, imgurl: string, moneyUnit: string, numberOfDigits: number, isTrade: boolean };

export type CPProductPartsFragment = { __typename?: 'CP_Product', id: number, cppay_id: number, seller_id: number, name: string, desciption: string, qty: number, price: number, imgurl: string, createdAt: any };

export type CPTmpTradePartsFragment = { __typename?: 'CP_TradeTmpCode', id: number, product_id: number, cppay_id: number, seller_id: number, seller_name: string, name: string, qty: number, price: number, sumPrice: number, code: string };

export type CP_BillPartsFragment = { __typename?: 'CP_Bill', id: number, cppay_id: number, seller_id: number, seller_name: string, consumer_id: number, consumer_name: string, kind: Types.BILL_KIND_TYPE, name: string, desciption: string, qty: number, price: number, sumPrice: number, createdAt: any };

export type CP_BankBookPartsFragment = { __typename?: 'CP_BankBook', id: number, cppay_id: number, user_id: number, recordtype: Types.RECORD_TYPE, kind: Types.BILL_KIND_TYPE, desciption: string, beforeMoney: number, price: number, resultMoney: number, insti_id: number, broker_id: number, createdAt: any, sender_name: string, receiver_name: string };

export const CPUserBasicPartsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CPUserBasicParts"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CP_User"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"mainId"}},{"kind":"Field","name":{"kind":"Name","value":"number"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"position"}},{"kind":"Field","name":{"kind":"Name","value":"money"}}]}}]} as unknown as DocumentNode<CPUserBasicPartsFragment, unknown>;
export const CPPayPartsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CPPayParts"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CP_Pay"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"user_id"}},{"kind":"Field","name":{"kind":"Name","value":"className"}},{"kind":"Field","name":{"kind":"Name","value":"schoolName"}},{"kind":"Field","name":{"kind":"Name","value":"classTh"}},{"kind":"Field","name":{"kind":"Name","value":"classNum"}},{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"imgurl"}},{"kind":"Field","name":{"kind":"Name","value":"moneyUnit"}},{"kind":"Field","name":{"kind":"Name","value":"numberOfDigits"}},{"kind":"Field","name":{"kind":"Name","value":"isTrade"}}]}}]} as unknown as DocumentNode<CPPayPartsFragment, unknown>;
export const CPProductPartsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CPProductParts"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CP_Product"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"cppay_id"}},{"kind":"Field","name":{"kind":"Name","value":"seller_id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"desciption"}},{"kind":"Field","name":{"kind":"Name","value":"qty"}},{"kind":"Field","name":{"kind":"Name","value":"price"}},{"kind":"Field","name":{"kind":"Name","value":"imgurl"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}}]} as unknown as DocumentNode<CPProductPartsFragment, unknown>;
export const CPTmpTradePartsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CPTmpTradeParts"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CP_TradeTmpCode"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"product_id"}},{"kind":"Field","name":{"kind":"Name","value":"cppay_id"}},{"kind":"Field","name":{"kind":"Name","value":"seller_id"}},{"kind":"Field","name":{"kind":"Name","value":"seller_name"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"qty"}},{"kind":"Field","name":{"kind":"Name","value":"price"}},{"kind":"Field","name":{"kind":"Name","value":"sumPrice"}},{"kind":"Field","name":{"kind":"Name","value":"code"}}]}}]} as unknown as DocumentNode<CPTmpTradePartsFragment, unknown>;
export const CP_BillPartsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CP_BillParts"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CP_Bill"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"cppay_id"}},{"kind":"Field","name":{"kind":"Name","value":"seller_id"}},{"kind":"Field","name":{"kind":"Name","value":"seller_name"}},{"kind":"Field","name":{"kind":"Name","value":"consumer_id"}},{"kind":"Field","name":{"kind":"Name","value":"consumer_name"}},{"kind":"Field","name":{"kind":"Name","value":"kind"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"desciption"}},{"kind":"Field","name":{"kind":"Name","value":"qty"}},{"kind":"Field","name":{"kind":"Name","value":"price"}},{"kind":"Field","name":{"kind":"Name","value":"sumPrice"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}}]}}]} as unknown as DocumentNode<CP_BillPartsFragment, unknown>;
export const CP_BankBookPartsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"CP_BankBookParts"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"CP_BankBook"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"cppay_id"}},{"kind":"Field","name":{"kind":"Name","value":"user_id"}},{"kind":"Field","name":{"kind":"Name","value":"recordtype"}},{"kind":"Field","name":{"kind":"Name","value":"kind"}},{"kind":"Field","name":{"kind":"Name","value":"desciption"}},{"kind":"Field","name":{"kind":"Name","value":"beforeMoney"}},{"kind":"Field","name":{"kind":"Name","value":"price"}},{"kind":"Field","name":{"kind":"Name","value":"resultMoney"}},{"kind":"Field","name":{"kind":"Name","value":"insti_id"}},{"kind":"Field","name":{"kind":"Name","value":"broker_id"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"sender_name"}},{"kind":"Field","name":{"kind":"Name","value":"receiver_name"}}]}}]} as unknown as DocumentNode<CP_BankBookPartsFragment, unknown>;